// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: systemdata.proto

package com.gpigc.proto;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SystemDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string systemId = 1;
    /**
     * <code>required string systemId = 1;</code>
     */
    boolean hasSystemId();
    /**
     * <code>required string systemId = 1;</code>
     */
    java.lang.String getSystemId();
    /**
     * <code>required string systemId = 1;</code>
     */
    com.google.protobuf.ByteString
        getSystemIdBytes();

    // required uint64 timestamp = 2;
    /**
     * <code>required uint64 timestamp = 2;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required uint64 timestamp = 2;</code>
     */
    long getTimestamp();

    // repeated .tutorial.SystemData.Datum datum = 3;
    /**
     * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
     */
    java.util.List<com.gpigc.proto.Protos.SystemData.Datum> 
        getDatumList();
    /**
     * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
     */
    com.gpigc.proto.Protos.SystemData.Datum getDatum(int index);
    /**
     * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
     */
    int getDatumCount();
    /**
     * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
     */
    java.util.List<? extends com.gpigc.proto.Protos.SystemData.DatumOrBuilder> 
        getDatumOrBuilderList();
    /**
     * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
     */
    com.gpigc.proto.Protos.SystemData.DatumOrBuilder getDatumOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.SystemData}
   */
  public static final class SystemData extends
      com.google.protobuf.GeneratedMessage
      implements SystemDataOrBuilder {
    // Use SystemData.newBuilder() to construct.
    private SystemData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SystemData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SystemData defaultInstance;
    public static SystemData getDefaultInstance() {
      return defaultInstance;
    }

    public SystemData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SystemData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              systemId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readUInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                datum_ = new java.util.ArrayList<com.gpigc.proto.Protos.SystemData.Datum>();
                mutable_bitField0_ |= 0x00000004;
              }
              datum_.add(input.readMessage(com.gpigc.proto.Protos.SystemData.Datum.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          datum_ = java.util.Collections.unmodifiableList(datum_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gpigc.proto.Protos.internal_static_tutorial_SystemData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gpigc.proto.Protos.internal_static_tutorial_SystemData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gpigc.proto.Protos.SystemData.class, com.gpigc.proto.Protos.SystemData.Builder.class);
    }

    public static com.google.protobuf.Parser<SystemData> PARSER =
        new com.google.protobuf.AbstractParser<SystemData>() {
      public SystemData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SystemData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SystemData> getParserForType() {
      return PARSER;
    }

    public interface DatumOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string key = 1;
      /**
       * <code>required string key = 1;</code>
       */
      boolean hasKey();
      /**
       * <code>required string key = 1;</code>
       */
      java.lang.String getKey();
      /**
       * <code>required string key = 1;</code>
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      // required string value = 2;
      /**
       * <code>required string value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>required string value = 2;</code>
       */
      java.lang.String getValue();
      /**
       * <code>required string value = 2;</code>
       */
      com.google.protobuf.ByteString
          getValueBytes();
    }
    /**
     * Protobuf type {@code tutorial.SystemData.Datum}
     */
    public static final class Datum extends
        com.google.protobuf.GeneratedMessage
        implements DatumOrBuilder {
      // Use Datum.newBuilder() to construct.
      private Datum(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Datum(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Datum defaultInstance;
      public static Datum getDefaultInstance() {
        return defaultInstance;
      }

      public Datum getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Datum(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                key_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                value_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gpigc.proto.Protos.internal_static_tutorial_SystemData_Datum_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gpigc.proto.Protos.internal_static_tutorial_SystemData_Datum_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gpigc.proto.Protos.SystemData.Datum.class, com.gpigc.proto.Protos.SystemData.Datum.Builder.class);
      }

      public static com.google.protobuf.Parser<Datum> PARSER =
          new com.google.protobuf.AbstractParser<Datum>() {
        public Datum parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Datum(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Datum> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private java.lang.Object key_;
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private java.lang.Object value_;
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        key_ = "";
        value_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.gpigc.proto.Protos.SystemData.Datum parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.gpigc.proto.Protos.SystemData.Datum parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.gpigc.proto.Protos.SystemData.Datum parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.gpigc.proto.Protos.SystemData.Datum parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.gpigc.proto.Protos.SystemData.Datum parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.gpigc.proto.Protos.SystemData.Datum parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.gpigc.proto.Protos.SystemData.Datum parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.gpigc.proto.Protos.SystemData.Datum parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.gpigc.proto.Protos.SystemData.Datum parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.gpigc.proto.Protos.SystemData.Datum parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.gpigc.proto.Protos.SystemData.Datum prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code tutorial.SystemData.Datum}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.gpigc.proto.Protos.SystemData.DatumOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.gpigc.proto.Protos.internal_static_tutorial_SystemData_Datum_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.gpigc.proto.Protos.internal_static_tutorial_SystemData_Datum_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.gpigc.proto.Protos.SystemData.Datum.class, com.gpigc.proto.Protos.SystemData.Datum.Builder.class);
        }

        // Construct using com.gpigc.proto.Protos.SystemData.Datum.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.gpigc.proto.Protos.internal_static_tutorial_SystemData_Datum_descriptor;
        }

        public com.gpigc.proto.Protos.SystemData.Datum getDefaultInstanceForType() {
          return com.gpigc.proto.Protos.SystemData.Datum.getDefaultInstance();
        }

        public com.gpigc.proto.Protos.SystemData.Datum build() {
          com.gpigc.proto.Protos.SystemData.Datum result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.gpigc.proto.Protos.SystemData.Datum buildPartial() {
          com.gpigc.proto.Protos.SystemData.Datum result = new com.gpigc.proto.Protos.SystemData.Datum(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.gpigc.proto.Protos.SystemData.Datum) {
            return mergeFrom((com.gpigc.proto.Protos.SystemData.Datum)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.gpigc.proto.Protos.SystemData.Datum other) {
          if (other == com.gpigc.proto.Protos.SystemData.Datum.getDefaultInstance()) return this;
          if (other.hasKey()) {
            bitField0_ |= 0x00000001;
            key_ = other.key_;
            onChanged();
          }
          if (other.hasValue()) {
            bitField0_ |= 0x00000002;
            value_ = other.value_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasKey()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.gpigc.proto.Protos.SystemData.Datum parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.gpigc.proto.Protos.SystemData.Datum) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string key = 1;
        private java.lang.Object key_ = "";
        /**
         * <code>required string key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string key = 1;</code>
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }

        // required string value = 2;
        private java.lang.Object value_ = "";
        /**
         * <code>required string value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string value = 2;</code>
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string value = 2;</code>
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:tutorial.SystemData.Datum)
      }

      static {
        defaultInstance = new Datum(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:tutorial.SystemData.Datum)
    }

    private int bitField0_;
    // required string systemId = 1;
    public static final int SYSTEMID_FIELD_NUMBER = 1;
    private java.lang.Object systemId_;
    /**
     * <code>required string systemId = 1;</code>
     */
    public boolean hasSystemId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string systemId = 1;</code>
     */
    public java.lang.String getSystemId() {
      java.lang.Object ref = systemId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          systemId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string systemId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSystemIdBytes() {
      java.lang.Object ref = systemId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        systemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>required uint64 timestamp = 2;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // repeated .tutorial.SystemData.Datum datum = 3;
    public static final int DATUM_FIELD_NUMBER = 3;
    private java.util.List<com.gpigc.proto.Protos.SystemData.Datum> datum_;
    /**
     * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
     */
    public java.util.List<com.gpigc.proto.Protos.SystemData.Datum> getDatumList() {
      return datum_;
    }
    /**
     * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
     */
    public java.util.List<? extends com.gpigc.proto.Protos.SystemData.DatumOrBuilder> 
        getDatumOrBuilderList() {
      return datum_;
    }
    /**
     * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
     */
    public int getDatumCount() {
      return datum_.size();
    }
    /**
     * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
     */
    public com.gpigc.proto.Protos.SystemData.Datum getDatum(int index) {
      return datum_.get(index);
    }
    /**
     * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
     */
    public com.gpigc.proto.Protos.SystemData.DatumOrBuilder getDatumOrBuilder(
        int index) {
      return datum_.get(index);
    }

    private void initFields() {
      systemId_ = "";
      timestamp_ = 0L;
      datum_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSystemId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDatumCount(); i++) {
        if (!getDatum(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSystemIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, timestamp_);
      }
      for (int i = 0; i < datum_.size(); i++) {
        output.writeMessage(3, datum_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSystemIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      for (int i = 0; i < datum_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, datum_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gpigc.proto.Protos.SystemData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gpigc.proto.Protos.SystemData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gpigc.proto.Protos.SystemData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gpigc.proto.Protos.SystemData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gpigc.proto.Protos.SystemData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gpigc.proto.Protos.SystemData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gpigc.proto.Protos.SystemData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gpigc.proto.Protos.SystemData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gpigc.proto.Protos.SystemData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gpigc.proto.Protos.SystemData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gpigc.proto.Protos.SystemData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.SystemData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gpigc.proto.Protos.SystemDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gpigc.proto.Protos.internal_static_tutorial_SystemData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gpigc.proto.Protos.internal_static_tutorial_SystemData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gpigc.proto.Protos.SystemData.class, com.gpigc.proto.Protos.SystemData.Builder.class);
      }

      // Construct using com.gpigc.proto.Protos.SystemData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDatumFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        systemId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (datumBuilder_ == null) {
          datum_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          datumBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gpigc.proto.Protos.internal_static_tutorial_SystemData_descriptor;
      }

      public com.gpigc.proto.Protos.SystemData getDefaultInstanceForType() {
        return com.gpigc.proto.Protos.SystemData.getDefaultInstance();
      }

      public com.gpigc.proto.Protos.SystemData build() {
        com.gpigc.proto.Protos.SystemData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gpigc.proto.Protos.SystemData buildPartial() {
        com.gpigc.proto.Protos.SystemData result = new com.gpigc.proto.Protos.SystemData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.systemId_ = systemId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (datumBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            datum_ = java.util.Collections.unmodifiableList(datum_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.datum_ = datum_;
        } else {
          result.datum_ = datumBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gpigc.proto.Protos.SystemData) {
          return mergeFrom((com.gpigc.proto.Protos.SystemData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gpigc.proto.Protos.SystemData other) {
        if (other == com.gpigc.proto.Protos.SystemData.getDefaultInstance()) return this;
        if (other.hasSystemId()) {
          bitField0_ |= 0x00000001;
          systemId_ = other.systemId_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (datumBuilder_ == null) {
          if (!other.datum_.isEmpty()) {
            if (datum_.isEmpty()) {
              datum_ = other.datum_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureDatumIsMutable();
              datum_.addAll(other.datum_);
            }
            onChanged();
          }
        } else {
          if (!other.datum_.isEmpty()) {
            if (datumBuilder_.isEmpty()) {
              datumBuilder_.dispose();
              datumBuilder_ = null;
              datum_ = other.datum_;
              bitField0_ = (bitField0_ & ~0x00000004);
              datumBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDatumFieldBuilder() : null;
            } else {
              datumBuilder_.addAllMessages(other.datum_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSystemId()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        for (int i = 0; i < getDatumCount(); i++) {
          if (!getDatum(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gpigc.proto.Protos.SystemData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gpigc.proto.Protos.SystemData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string systemId = 1;
      private java.lang.Object systemId_ = "";
      /**
       * <code>required string systemId = 1;</code>
       */
      public boolean hasSystemId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string systemId = 1;</code>
       */
      public java.lang.String getSystemId() {
        java.lang.Object ref = systemId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          systemId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string systemId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSystemIdBytes() {
        java.lang.Object ref = systemId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          systemId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string systemId = 1;</code>
       */
      public Builder setSystemId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        systemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string systemId = 1;</code>
       */
      public Builder clearSystemId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        systemId_ = getDefaultInstance().getSystemId();
        onChanged();
        return this;
      }
      /**
       * <code>required string systemId = 1;</code>
       */
      public Builder setSystemIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        systemId_ = value;
        onChanged();
        return this;
      }

      // required uint64 timestamp = 2;
      private long timestamp_ ;
      /**
       * <code>required uint64 timestamp = 2;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // repeated .tutorial.SystemData.Datum datum = 3;
      private java.util.List<com.gpigc.proto.Protos.SystemData.Datum> datum_ =
        java.util.Collections.emptyList();
      private void ensureDatumIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          datum_ = new java.util.ArrayList<com.gpigc.proto.Protos.SystemData.Datum>(datum_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.gpigc.proto.Protos.SystemData.Datum, com.gpigc.proto.Protos.SystemData.Datum.Builder, com.gpigc.proto.Protos.SystemData.DatumOrBuilder> datumBuilder_;

      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public java.util.List<com.gpigc.proto.Protos.SystemData.Datum> getDatumList() {
        if (datumBuilder_ == null) {
          return java.util.Collections.unmodifiableList(datum_);
        } else {
          return datumBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public int getDatumCount() {
        if (datumBuilder_ == null) {
          return datum_.size();
        } else {
          return datumBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public com.gpigc.proto.Protos.SystemData.Datum getDatum(int index) {
        if (datumBuilder_ == null) {
          return datum_.get(index);
        } else {
          return datumBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public Builder setDatum(
          int index, com.gpigc.proto.Protos.SystemData.Datum value) {
        if (datumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatumIsMutable();
          datum_.set(index, value);
          onChanged();
        } else {
          datumBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public Builder setDatum(
          int index, com.gpigc.proto.Protos.SystemData.Datum.Builder builderForValue) {
        if (datumBuilder_ == null) {
          ensureDatumIsMutable();
          datum_.set(index, builderForValue.build());
          onChanged();
        } else {
          datumBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public Builder addDatum(com.gpigc.proto.Protos.SystemData.Datum value) {
        if (datumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatumIsMutable();
          datum_.add(value);
          onChanged();
        } else {
          datumBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public Builder addDatum(
          int index, com.gpigc.proto.Protos.SystemData.Datum value) {
        if (datumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatumIsMutable();
          datum_.add(index, value);
          onChanged();
        } else {
          datumBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public Builder addDatum(
          com.gpigc.proto.Protos.SystemData.Datum.Builder builderForValue) {
        if (datumBuilder_ == null) {
          ensureDatumIsMutable();
          datum_.add(builderForValue.build());
          onChanged();
        } else {
          datumBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public Builder addDatum(
          int index, com.gpigc.proto.Protos.SystemData.Datum.Builder builderForValue) {
        if (datumBuilder_ == null) {
          ensureDatumIsMutable();
          datum_.add(index, builderForValue.build());
          onChanged();
        } else {
          datumBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public Builder addAllDatum(
          java.lang.Iterable<? extends com.gpigc.proto.Protos.SystemData.Datum> values) {
        if (datumBuilder_ == null) {
          ensureDatumIsMutable();
          super.addAll(values, datum_);
          onChanged();
        } else {
          datumBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public Builder clearDatum() {
        if (datumBuilder_ == null) {
          datum_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          datumBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public Builder removeDatum(int index) {
        if (datumBuilder_ == null) {
          ensureDatumIsMutable();
          datum_.remove(index);
          onChanged();
        } else {
          datumBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public com.gpigc.proto.Protos.SystemData.Datum.Builder getDatumBuilder(
          int index) {
        return getDatumFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public com.gpigc.proto.Protos.SystemData.DatumOrBuilder getDatumOrBuilder(
          int index) {
        if (datumBuilder_ == null) {
          return datum_.get(index);  } else {
          return datumBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public java.util.List<? extends com.gpigc.proto.Protos.SystemData.DatumOrBuilder> 
           getDatumOrBuilderList() {
        if (datumBuilder_ != null) {
          return datumBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(datum_);
        }
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public com.gpigc.proto.Protos.SystemData.Datum.Builder addDatumBuilder() {
        return getDatumFieldBuilder().addBuilder(
            com.gpigc.proto.Protos.SystemData.Datum.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public com.gpigc.proto.Protos.SystemData.Datum.Builder addDatumBuilder(
          int index) {
        return getDatumFieldBuilder().addBuilder(
            index, com.gpigc.proto.Protos.SystemData.Datum.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.SystemData.Datum datum = 3;</code>
       */
      public java.util.List<com.gpigc.proto.Protos.SystemData.Datum.Builder> 
           getDatumBuilderList() {
        return getDatumFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.gpigc.proto.Protos.SystemData.Datum, com.gpigc.proto.Protos.SystemData.Datum.Builder, com.gpigc.proto.Protos.SystemData.DatumOrBuilder> 
          getDatumFieldBuilder() {
        if (datumBuilder_ == null) {
          datumBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.gpigc.proto.Protos.SystemData.Datum, com.gpigc.proto.Protos.SystemData.Datum.Builder, com.gpigc.proto.Protos.SystemData.DatumOrBuilder>(
                  datum_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          datum_ = null;
        }
        return datumBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.SystemData)
    }

    static {
      defaultInstance = new SystemData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.SystemData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_SystemData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_SystemData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_SystemData_Datum_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_SystemData_Datum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020systemdata.proto\022\010tutorial\"\201\001\n\nSystemD" +
      "ata\022\020\n\010systemId\030\001 \002(\t\022\021\n\ttimestamp\030\002 \002(\004" +
      "\022)\n\005datum\030\003 \003(\0132\032.tutorial.SystemData.Da" +
      "tum\032#\n\005Datum\022\013\n\003key\030\001 \002(\t\022\r\n\005value\030\002 \002(\t" +
      "B\031\n\017com.gpigc.protoB\006Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_SystemData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_SystemData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_SystemData_descriptor,
              new java.lang.String[] { "SystemId", "Timestamp", "Datum", });
          internal_static_tutorial_SystemData_Datum_descriptor =
            internal_static_tutorial_SystemData_descriptor.getNestedTypes().get(0);
          internal_static_tutorial_SystemData_Datum_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_SystemData_Datum_descriptor,
              new java.lang.String[] { "Key", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
